// <auto-generated />
using System;
using JOIEnergy.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JOIEnergy.Migrations
{
    [DbContext(typeof(JoiDBContext))]
    partial class JoiDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JOIEnergy.Domain.PlanDetailsDB", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("EnergySupplier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PlanId");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("JOIEnergy.Domain.Reading", b =>
                {
                    b.Property<int>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReadingId"));

                    b.Property<string>("SmartMeterId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ReadingId");

                    b.HasIndex("SmartMeterId");

                    b.ToTable("Readings", (string)null);
                });

            modelBuilder.Entity("JOIEnergy.Domain.SmartMeterIDDetailsDB", b =>
                {
                    b.Property<string>("SmartMeterId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("SmartMeterId");

                    b.HasIndex("PlanId");

                    b.ToTable("SmartMeters", (string)null);
                });

            modelBuilder.Entity("JOIEnergy.Domain.Reading", b =>
                {
                    b.HasOne("JOIEnergy.Domain.SmartMeterIDDetailsDB", "SmartMeter")
                        .WithMany("Readings")
                        .HasForeignKey("SmartMeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmartMeter");
                });

            modelBuilder.Entity("JOIEnergy.Domain.SmartMeterIDDetailsDB", b =>
                {
                    b.HasOne("JOIEnergy.Domain.PlanDetailsDB", "PlanDetails")
                        .WithMany("SmartMeters")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanDetails");
                });

            modelBuilder.Entity("JOIEnergy.Domain.PlanDetailsDB", b =>
                {
                    b.Navigation("SmartMeters");
                });

            modelBuilder.Entity("JOIEnergy.Domain.SmartMeterIDDetailsDB", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
